application: cs373-54270-teamd
version: 6
runtime: python
api_version: 1

handlers:
- url: /js
  static_dir: js

- url: /style
  static_dir: style

- url: /
  static_dir: static_html

- url: /.*
  script: index.py

